name: MLflow-CI-Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/TimothyS710/Membangun_Sistem_ML.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CI_MODEL_OUTPUT: ${{ github.workspace }}/model_output_final

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn

    - name: Run MLflow Project
      run: |
        cd Workflow-CI
        mlflow run . --env-manager=local

    - name: Check Artifacts (Debugging)
      run: |
        ls -R ${{ env.CI_MODEL_OUTPUT }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/credit-risk-model:latest ./Workflow-CI
        docker push ${{ secrets.DOCKER_USERNAME }}/credit-risk-model:latest