name: MLflow-CI-Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/TimothyS710/Membangun_Sistem_ML.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # INI KUNCINYA: Kita tentukan satu alamat pasti untuk output model
  CI_MODEL_OUTPUT: ${{ github.workspace }}/model_output_final

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn

    - name: Run MLflow Project
      run: |
        cd MLProject
        # Script python akan membaca variabel CI_MODEL_OUTPUT dari env di atas
        mlflow run . --env-manager=local

    - name: Check Artifacts (Debugging)
      run: |
        echo "Memeriksa apakah model berhasil disimpan..."
        ls -R ${{ env.CI_MODEL_OUTPUT }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        echo "üê≥ Building Docker from Fixed Path: ${{ env.CI_MODEL_OUTPUT }}"
        
        mlflow models build-docker \
          --model-uri "${{ env.CI_MODEL_OUTPUT }}" \
          --name "timothys710/submission-finall:latest" \
          --enable-mlserver
        
        docker push timothys710/submission-finall:latest