name: MLflow-CI-Pipeline

on:
  push:
    branches:
      - main

# --- PERBAIKAN UTAMA: GLOBAL ENVIRONMENT ---
env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/TimothyS710/Membangun_Sistem_ML.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install Dependencies
    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn

    # 4. Run MLflow Project (Training)
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    # 5. Get Run ID
    - name: Get Latest Run ID
      id: get_run_id
      run: |
        # Script ini akan otomatis pakai URI dari Global Environment di atas
        RUN_ID=$(python -c "import mlflow; import os; print(mlflow.search_runs(experiment_names=['Submission_Final_Workflow'], order_by=['start_time DESC']).iloc[0].run_id)")
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        echo "üèÜ Latest Run ID found: $RUN_ID"

    # 6. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Build & Push Docker Image
    - name: Build & Push Docker Image
      run: |
        # MLflow akan otomatis baca URI dari Global Env, jadi dia gak akan nyasar ke SQLite lagi
        mlflow models build-docker \
          --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" \
          --name "timothys710/submission-finall:latest" \
          --enable-mlserver
        
        docker push timothys710/submission-finall:latest