name: MLflow-CI-Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/TimothyS710/Membangun_Sistem_ML.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn

    - name: Run MLflow Project
      id: run_mlflow
      run: |
        cd MLProject
        # Jalankan project dan simpan output log ke file
        mlflow run . --env-manager=local > run_log.txt 2>&1
        
        # Tampilkan log ke layar (supaya kita bisa baca jika error)
        cat run_log.txt
        
        # Tangkap Run ID menggunakan grep dari output log
        # Pola yang dicari: "Run (ID: xxxx) succeeded"
        RUN_ID=$(grep -oP "Run \(ID: \K[a-f0-9]+" run_log.txt | head -1)
        
        if [ -z "$RUN_ID" ]; then
          echo "‚ùå Gagal menemukan Run ID! Cek log di atas."
          exit 1
        fi
        
        echo "‚úÖ Run ID Baru ditemukan: $RUN_ID"
        # Simpan ke Output GitHub Actions
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        # Ambil variable dari step 'run_mlflow'
        TARGET_RUN_ID=${{ steps.run_mlflow.outputs.run_id }}
        
        echo "üê≥ Building Docker for Run ID: $TARGET_RUN_ID"
        
        mlflow models build-docker \
          --model-uri "runs:/$TARGET_RUN_ID/model" \
          --name "timothys710/submission-finall:latest" \
          --enable-mlserver
        
        docker push timothys710/submission-finall:latest