name: MLflow-CI-Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/TimothyS710/Membangun_Sistem_ML.mlflow"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn

    - name: Run Training Script
      id: run_mlflow
      run: |
        cd MLProject
        python modelling.py > run_log.txt 2>&1
        cat run_log.txt
        RUN_ID=$(grep -oP "RUN_ID_CI:\K[a-f0-9]+" run_log.txt | tail -1)
        
        if [ -z "$RUN_ID" ]; then
          echo "Failed to find Run ID"
          exit 1
        fi
        
        echo "Run ID found: $RUN_ID"
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Wait for DagsHub Sync
      run: |
        echo "Waiting 30s for artifact propagation..."
        sleep 30

    - name: Verify Artifacts Existence
      env:
        RUN_ID: ${{ steps.run_mlflow.outputs.run_id }}
      run: |
        mlflow artifacts list --run-id $RUN_ID

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        TARGET_RUN_ID=${{ steps.run_mlflow.outputs.run_id }}
        mlflow models build-docker \
          --model-uri "runs:/$TARGET_RUN_ID/model" \
          --name "timothys710/submission-finall:latest" \
          --enable-mlserver
        docker push timothys710/submission-finall:latest